name: Restrict Commits

on:
  push:
    branches:
      - "**"  # 모든 브랜치에 대해 검사

jobs:
  validate-user:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Validate GitHub Username
      run: |
        # 허용할 GitHub 사용자명 리스트
        ALLOWED_USERS=("langchainopentutorial" "teddylee777" "sohyunwriter" "BAEM1N")

        # GitHub Actions의 기본 환경변수에서 푸시한 사용자명 확인
        PUSH_ACTOR=$GITHUB_ACTOR

        echo "Push Actor: $PUSH_ACTOR"

        # 사용자명 검증
        if [[ ! " ${ALLOWED_USERS[@]} " =~ " ${PUSH_ACTOR} " ]]; then
          echo "❌ Unauthorized push by $PUSH_ACTOR"
          echo "This commit will not be accepted into the repository."
          exit 1
        fi

        echo "✅ Push authorized for $PUSH_ACTOR"
